// #define DEFAULT_CURSOR 0
#define ARROW_CURSOR 1
#define BEAM_CURSOR 2
#define CROSS_CURSOR 3
#define HAND_CURSOR 4
#define HORIZONTAL_RESIZE_CURSOR 5
#define VERTICAL_RESIZE_CURSOR 6
#define DIAGONAL_1_RESIZE_CURSOR 7
#define DIAGONAL_2_RESIZE_CURSOR 8
#define PAN_CURSOR 9
#define UNAVAILABLE_CURSOR 10